"""initial_schema

Revision ID: b872aac44cb8
Revises: 
Create Date: 2026-03-30 00:55:07.780909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b872aac44cb8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('benchmark_suites',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('task_mode', sa.Text(), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('datasets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('version', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('local_path', sa.Text(), nullable=False),
    sa.Column('schema_version', sa.Text(), nullable=True),
    sa.Column('task_mode', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hardware_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hostname', sa.Text(), nullable=True),
    sa.Column('os_name', sa.Text(), nullable=False),
    sa.Column('os_version', sa.Text(), nullable=True),
    sa.Column('cpu_model', sa.Text(), nullable=False),
    sa.Column('cpu_cores', sa.Integer(), nullable=False),
    sa.Column('cpu_threads', sa.Integer(), nullable=False),
    sa.Column('ram_bytes', sa.Integer(), nullable=False),
    sa.Column('gpu_vendor', sa.Text(), nullable=True),
    sa.Column('gpu_model', sa.Text(), nullable=True),
    sa.Column('vram_bytes', sa.Integer(), nullable=True),
    sa.Column('cuda_version', sa.Text(), nullable=True),
    sa.Column('driver_version', sa.Text(), nullable=True),
    sa.Column('capabilities_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_catalog',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('source_ref', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('family', sa.Text(), nullable=True),
    sa.Column('task_modes_json', sa.Text(), nullable=False),
    sa.Column('format', sa.Text(), nullable=True),
    sa.Column('params_billions', sa.Float(), nullable=True),
    sa.Column('context_length', sa.Integer(), nullable=True),
    sa.Column('license_text', sa.Text(), nullable=True),
    sa.Column('min_ram_bytes', sa.Integer(), nullable=True),
    sa.Column('min_vram_bytes', sa.Integer(), nullable=True),
    sa.Column('quant_options_json', sa.Text(), nullable=True),
    sa.Column('backend_support_json', sa.Text(), nullable=True),
    sa.Column('supports_lora', sa.Integer(), nullable=False),
    sa.Column('supports_qlora', sa.Integer(), nullable=False),
    sa.Column('guardrail_role', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider_accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider_type', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('secret_ref', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('meta_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('model_cache_dir', sa.Text(), nullable=False),
    sa.Column('allow_remote_providers', sa.Integer(), nullable=False),
    sa.Column('default_task_mode', sa.Text(), nullable=False),
    sa.Column('privacy_mode', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('installed_models',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('catalog_id', sa.String(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('local_name', sa.Text(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=True),
    sa.Column('base_model_id', sa.String(), nullable=True),
    sa.Column('adapter_path', sa.Text(), nullable=True),
    sa.Column('format', sa.Text(), nullable=True),
    sa.Column('quantization', sa.Text(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('is_temporary', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['base_model_id'], ['installed_models.id'], ),
    sa.ForeignKeyConstraint(['catalog_id'], ['model_catalog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('benchmark_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('suite_id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('hardware_profile_id', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=True),
    sa.Column('backend', sa.Text(), nullable=False),
    sa.Column('scenario', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('summary_json', sa.Text(), nullable=True),
    sa.Column('raw_metrics_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['hardware_profile_id'], ['hardware_profiles.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['installed_models.id'], ),
    sa.ForeignKeyConstraint(['suite_id'], ['benchmark_suites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('optimization_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('source_model_id', sa.String(), nullable=False),
    sa.Column('output_model_id', sa.String(), nullable=True),
    sa.Column('method', sa.Text(), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('diff_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['output_model_id'], ['installed_models.id'], ),
    sa.ForeignKeyConstraint(['source_model_id'], ['installed_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('base_model_id', sa.String(), nullable=False),
    sa.Column('output_model_id', sa.String(), nullable=True),
    sa.Column('dataset_id', sa.String(), nullable=False),
    sa.Column('optimizer', sa.Text(), nullable=False),
    sa.Column('learning_rate', sa.Float(), nullable=False),
    sa.Column('epochs', sa.Integer(), nullable=False),
    sa.Column('batch_size', sa.Integer(), nullable=False),
    sa.Column('gradient_accumulation', sa.Integer(), nullable=False),
    sa.Column('lora_r', sa.Integer(), nullable=True),
    sa.Column('lora_alpha', sa.Integer(), nullable=True),
    sa.Column('lora_dropout', sa.Float(), nullable=True),
    sa.Column('target_modules_json', sa.Text(), nullable=True),
    sa.Column('train_metrics_json', sa.Text(), nullable=True),
    sa.Column('eval_metrics_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['base_model_id'], ['installed_models.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['output_model_id'], ['installed_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('benchmark_samples',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('benchmark_run_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.Text(), nullable=False),
    sa.Column('success', sa.Integer(), nullable=True),
    sa.Column('verifier_pass', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('score_json', sa.Text(), nullable=True),
    sa.Column('artifact_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['benchmark_run_id'], ['benchmark_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cyber_artifacts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('benchmark_run_id', sa.String(), nullable=True),
    sa.Column('model_id', sa.String(), nullable=True),
    sa.Column('artifact_type', sa.Text(), nullable=False),
    sa.Column('content_path', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['benchmark_run_id'], ['benchmark_runs.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['installed_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('report_type', sa.Text(), nullable=False),
    sa.Column('benchmark_run_id', sa.String(), nullable=True),
    sa.Column('output_path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['benchmark_run_id'], ['benchmark_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('validation_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('artifact_id', sa.String(), nullable=False),
    sa.Column('validator_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('output_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['cyber_artifacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validation_runs')
    op.drop_table('reports')
    op.drop_table('cyber_artifacts')
    op.drop_table('benchmark_samples')
    op.drop_table('training_runs')
    op.drop_table('optimization_runs')
    op.drop_table('benchmark_runs')
    op.drop_table('installed_models')
    op.drop_table('settings')
    op.drop_table('provider_accounts')
    op.drop_table('model_catalog')
    op.drop_table('jobs')
    op.drop_table('hardware_profiles')
    op.drop_table('datasets')
    op.drop_table('benchmark_suites')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
